### PR TITLE
Add link to documentation in README

### PR DESCRIPTION
**Pull request by jessitron**
Google gives me the source repo, but I really want the docs. It'd be nice to get from one to the other.

### CODE REVIEW

**Comment by jvoigtlaender** [comment]
Close this for the same reason as https://github.com/evancz/elm-effects/issues/21?

**Comment by evancz** [comment]
Yeah, I think it's weird to do this. When we revamp the package site we should figure out how to get our results higher up there. @rtfeldman has talked about this before I think. In any case, I feel like this solution is not "the right way" and we don't have enough info to know if it is an appropriate stopgap.

**Comment by rtfeldman** [comment]
@evancz GitHub lets you specify a website for the repo; that's what I've been using for this, e.g. https://github.com/rtfeldman/elm-validate

**Comment by evancz** [comment]
Ah, I like that very much, great suggestion!

**Comment by evancz** [comment]
I'll try to do that on all my repos

**Pull request closed without merging**
